export const AGENTS = [
  {
    id: "compte-rendu-intervention",
    badge: "CRI",
    color: "#0D66D4",
    title: "Compte Rendu d'Intervention",
    to: "/compte_rendu_intervention",
    roles: ["agent", "admin"],
  },
  {
    id: "ppa-medico-social",
    badge: "PPAMS",
    color: "#42C4A1",
    title: "PPA Médico-Social",
    to: "/projet_personnalise_medico_social",
    roles: ["agent", "admin"],
  },
  {
    id: "ppa-social",
    badge: "PPAS",
    color: "#1294C3",
    title: "PPA Social",
    to: "/projet_personnalise_social",
    roles: ["agent", "admin"],
  },
  {
    id: "ecrit-educatif",
    badge: "ECRIT",
    color: "#F44E92",
    title: "Écrit Éducatif",
    to: "/ecrit_educatif",
    roles: ["agent", "admin"],
  },
  {
    id: "bilan-evaluation",
    badge: "BILAN",
    color: "#9B2CB6",
    title: "Bilan d'Évaluation",
    to: "/bilan_evaluation",
    roles: ["agent", "admin"],
  },
  {
    id: "compte-rendu-reunion",
    badge: "CRR",
    color: "#0D66D4",
    title: "Compte Rendu de Réunion",
    to: null,
    roles: ["direction", "admin"],
  },
  {
    id: "veille-professionnelle",
    badge: "VEILLE",
    color: "#1294C3",
    title: "Veille Professionnelle",
    to: null,
    roles: ["direction", "admin"],
  },
  {
    id: "reporting-mensuel",
    badge: "REPORT",
    color: "#42C4A1",
    title: "Reporting Mensuel",
    to: null,
    roles: ["direction", "admin"],
  },
  {
    id: "rapport-activite",
    badge: "RA",
    color: "#9B2CB6",
    title: "Rapport d'Activité",
    to: null,
    roles: ["direction", "admin"],
  },
  {
    id: "bilan-activite",
    badge: "BA",
    color: "#FCBE82",
    title: "Bilan d'Activité",
    to: null,
    roles: ["direction", "admin"],
  },
  {
    id: "projet-etablissement",
    badge: "PE",
    color: "#F44E92",
    title: "Projet d'Établissement",
    to: null,
    roles: ["direction", "admin"],
  },
  {
    id: "projet-service",
    badge: "PS",
    color: "#6CE4A8",
    title: "Projet de Service",
    to: null,
    roles: ["direction", "admin"],
  },
  {
    id: "evaluation-interne-externe",
    badge: "HAS",
    color: "#FC89A3",
    title: "Préparation Évaluation HAS",
    to: null,
    roles: ["direction", "admin"],
  },
  {
    id: "appel-projet",
    badge: "AAP",
    color: "#FCBE82",
    title: "Appel à Projet",
    to: null,
    roles: ["direction", "admin"],
  },
];
