export const AGENTS = [
  // ── Agents (couleurs froides : violet → indigo → bleu → ciel → cyan) ─────
  {
    id: "compte-rendu-intervention",
    badge: "CRI",
    color: "var(--bleu-fonce)",
    title: "Compte Rendu d'Intervention",
    to: "/compte_rendu_intervention",
    roles: ["agent", "admin"],
  },
  {
    id: "ppa-medico-social",
    badge: "PPAMS",
    color: "#4F72FF",
    title: "PPA Médico-Social",
    to: "/projet_personnalise_medico_social",
    roles: ["agent", "admin"],
  },
  {
    id: "ppa-social",
    badge: "PPAS",
    color: "#3B82F6",
    title: "PPA Social",
    to: "/projet_personnalise_social",
    roles: ["agent", "admin"],
  },
  {
    id: "ecrit-educatif",
    badge: "ECRIT",
    color: "#0EA5E9",
    title: "Écrit Éducatif",
    to: "/ecrit_educatif",
    roles: ["agent", "admin"],
  },
  {
    id: "bilan-evaluation",
    badge: "BILAN",
    color: "#06B6D4",
    title: "Bilan d'Évaluation",
    to: "/bilan_evaluation",
    roles: ["agent", "admin"],
  },
  // ── Direction (couleurs chaudes : rose → rouge → orange → ambre → or) ────
  {
    id: "compte-rendu-reunion",
    badge: "CRR",
    color: "#F43F5E",
    title: "Compte Rendu de Réunion",
    to: "/compte_rendu_reunion",
    roles: ["direction", "admin"],
  },
  {
    id: "veille-professionnelle",
    badge: "VEILLE",
    color: "#EF4444",
    title: "Veille Professionnelle",
    to: "/veille_professionnelle",
    roles: ["direction", "admin"],
  },
  {
    id: "reporting-mensuel",
    badge: "REPORT",
    color: "#F97316",
    title: "Reporting Mensuel",
    to: "/reporting_mensuel",
    roles: ["direction", "admin"],
  },
  {
    id: "rapport-activite",
    badge: "RA",
    color: "#FB923C",
    title: "Rapport d'Activité",
    to: "/rapport_activite",
    roles: ["direction", "admin"],
  },
  {
    id: "bilan-activite",
    badge: "BA",
    color: "#FBBF24",
    title: "Bilan d'Activité",
    to: "/bilan_activite",
    roles: ["direction", "admin"],
  },
  {
    id: "projet-etablissement",
    badge: "PE",
    color: "#F59E0B",
    title: "Projet d'Établissement",
    to: "/projet_etablissement",
    roles: ["direction", "admin"],
  },
  {
    id: "projet-service",
    badge: "PS",
    color: "#EAB308",
    title: "Projet de Service",
    to: "/projet_service",
    roles: ["direction", "admin"],
  },
  {
    id: "evaluation-interne-externe",
    badge: "HAS",
    color: "#D97706",
    title: "Préparation Évaluation HAS",
    to: "/evaluation_has",
    roles: ["direction", "admin"],
  },
  {
    id: "appel-projet",
    badge: "AAP",
    color: "#B45309",
    title: "Appel à Projet",
    to: "/appel_projet",
    roles: ["direction", "admin"],
  },
];
