export const AGENTS = [
  // ── Agents (couleurs froides) ────────────────────────────────────────────
  {
    id: "compte-rendu-intervention",
    badge: "CRI",
    color: "#673DE6",
    title: "Compte Rendu d'Intervention",
    to: "/compte_rendu_intervention",
    roles: ["agent", "admin"],
  },
  {
    id: "ppa-medico-social",
    badge: "PPAMS",
    color: "#42C4A1",
    title: "PPA Médico-Social",
    to: "/projet_personnalise_medico_social",
    roles: ["agent", "admin"],
  },
  {
    id: "ppa-social",
    badge: "PPAS",
    color: "#4C78FF",
    title: "PPA Social",
    to: "/projet_personnalise_social",
    roles: ["agent", "admin"],
  },
  {
    id: "ecrit-educatif",
    badge: "ECRIT",
    color: "#7B66FF",
    title: "Écrit Éducatif",
    to: "/ecrit_educatif",
    roles: ["agent", "admin"],
  },
  {
    id: "bilan-evaluation",
    badge: "BILAN",
    color: "#3AB0FF",
    title: "Bilan d'Évaluation",
    to: "/bilan_evaluation",
    roles: ["agent", "admin"],
  },
  // ── Direction (couleurs chaudes) ─────────────────────────────────────────
  {
    id: "compte-rendu-reunion",
    badge: "CRR",
    color: "#E11D48",
    title: "Compte Rendu de Réunion",
    to: "/compte_rendu_reunion",
    roles: ["direction", "admin"],
  },
  {
    id: "veille-professionnelle",
    badge: "VEILLE",
    color: "#EA580C",
    title: "Veille Professionnelle",
    to: "/veille_professionnelle",
    roles: ["direction", "admin"],
  },
  {
    id: "reporting-mensuel",
    badge: "REPORT",
    color: "#F97316",
    title: "Reporting Mensuel",
    to: "/reporting_mensuel",
    roles: ["direction", "admin"],
  },
  {
    id: "rapport-activite",
    badge: "RA",
    color: "#D97706",
    title: "Rapport d'Activité",
    to: "/rapport_activite",
    roles: ["direction", "admin"],
  },
  {
    id: "bilan-activite",
    badge: "BA",
    color: "#F59E0B",
    title: "Bilan d'Activité",
    to: "/bilan_activite",
    roles: ["direction", "admin"],
  },
  {
    id: "projet-etablissement",
    badge: "PE",
    color: "#F43F5E",
    title: "Projet d'Établissement",
    to: "/projet_etablissement",
    roles: ["direction", "admin"],
  },
  {
    id: "projet-service",
    badge: "PS",
    color: "#FB923C",
    title: "Projet de Service",
    to: "/projet_service",
    roles: ["direction", "admin"],
  },
  {
    id: "evaluation-interne-externe",
    badge: "HAS",
    color: "#DB2777",
    title: "Préparation Évaluation HAS",
    to: null,
    roles: ["direction", "admin"],
  },
  {
    id: "appel-projet",
    badge: "AAP",
    color: "#FBBF24",
    title: "Appel à Projet",
    to: null,
    roles: ["direction", "admin"],
  },
];
